GET http://localhost:3003/api/users
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "React patterns",
  "author": "Tommy Hill",
  "url": "https://reactpatterns.com/",
  "likes": 7
}


###
DELETE http://localhost:3003/api/blogs/607c83f393e22b560e1e0001

###
PUT http://localhost:3003/api/blogs/5a422b891b54a676234d17fa
Content-Type: application/json

{
  "likes": 12
}
 
